New koca branch
openssl/general-policies pull request #26
Opened 2022-09-09 13:29 UTC by mkoci-koca

2022-09-09 14:17 UTC, mattcaswell requested changes

2022-09-09 14:17 UTC, mattcaswell commented on policies/travel-policy.md
> +The Travel Authoriser or their designated representative is responsible
Who is the travel authoriser? Is this different to the travel approver?

2022-09-09 14:17 UTC, mattcaswell commented on policies/travel-policy.md
> +    finance@openssl.org attention to the Travel Approver for review.
Here it says travel approver....but above we said travel authoriser. Does it have to be the same person that originally approved the travel, or is it different?

2022-09-14 07:54 UTC, paulidale commented
Calling a vote on this policy as at f9f492230b08b648d6f89818987cdb42f9d34d90

We need this quickly in order to plan the upcoming face to face.  It is intended to review the policy and update in the near future.

2022-09-14 08:19 UTC, t-j-h commented
Vote +1

2022-09-14 08:19 UTC, iamamoose commented
+1

2022-09-14 08:52 UTC, paulidale commented
vote: +1

2022-09-14 10:22 UTC, tom-cosgrove-arm commented on policies/travel-policy.md
> +to time (subsequently known collectively as *Traveller*).
(collectively probably implies plural)

```suggestion
to time (subsequently known collectively as *Travellers*).
```

Also, note that much of the document uses second-person "you", while some uses "traveller(s)", so not consistent.

2022-09-14 10:40 UTC, mattcaswell commented
On the basis that we expect to revise this policy in the near future to take account of the various feedback comments I am happy to accept it as-is for now. It's not perfect but it is better and more complete than the previous travel policy.

Vote: +1

2022-09-14 16:48 UTC, mkoci-koca commented on policies/travel-policy.md
> +
To arrive 2 days prior and lose the comfort of traveling doesn't make sense. These are 2 different things. Suppose I come 2 days before I get a benefit to settle myself from jet lag. It doesn't help if I fly for more than 6 hours. 
So I would omit this column "Where flight class not available" .

2022-09-14 17:13 UTC, kroeckx commented
I'm voting 0

2022-09-14 22:31 UTC, paulidale commented
The vote passes 4 to 0 with one abstain and one not voted

2022-09-14 22:31 UTC, paulidale commented
Reopening so we don't forget about the comments

2022-09-20 12:54 UTC, mkoci-koca commented on policies/travel-policy.md
> +  | Manager and OMC member | US\$15,000 |
I understand that it should be approved by a manager and at least one OMC member.

2022-09-20 13:01 UTC, closed without merging