Minor edits of Time based releases policy
openssl/general-policies pull request #52
Opened 2023-08-09 08:53 UTC by t8m

This is to improve the rendering of the policy at www.openssl.org

2023-08-09 09:13 UTC, arapov requested changes

2023-08-09 10:38 UTC, t8m commented on policies/release-policy.md
> +committee under specific circumstances, such as:
It is intentional as the rendering on  https://www.openssl.org/policies/general/release-policy.html is confusing - it duplicates the footnote.

2023-08-09 10:51 UTC, arapov commented on policies/release-policy.md
> +committee under specific circumstances, such as:
I see, Ok then.

2023-08-09 10:52 UTC, arapov approved these changes

2023-08-09 12:21 UTC, t8m commented
One more OMC member approval needed before merging @iamamoose @paulidale @t-j-h ?

2023-08-09 12:22 UTC, t-j-h commented
Approved with the minor changes.

2023-08-09 12:22 UTC, t-j-h approved these changes

2023-08-09 21:29 UTC, paulidale approved these changes

2023-08-10 08:26 UTC, t8m commented
@mattcaswell can you please push this? I do not have write access to the primary repo for general-policies.

2023-08-11 00:55 UTC, paulidale commented
Pushed.

2023-08-11 00:55 UTC, closed without merging