Update to Payment Run Schedule
openssl/general-policies pull request #55
Opened 2023-10-05 03:51 UTC by TamaraDale

updated Contractor invoicing payment run schedule for 2024

2023-10-05 09:21 UTC, t8m commented
Tam, could you please rebase this onto fresh master branch? Or redo the commit from scratch based on fresh master branch? There are two unrelated commits.

2023-10-05 09:21 UTC, mattcaswell commented
There seems to be some spurious commits in here about the sponsorship policy

2023-10-05 14:52 UTC, arapov requested changes

2023-10-05 14:52 UTC, arapov commented on votes/vote-20230629-sponsorship-policy.txt
Is this something erroneous? It doesn't like something that should be in this PR.

The schedule is all right, I would approve it - if not this vote file here.

2023-10-05 20:14 UTC, t-j-h commented on votes/vote-20230629-sponsorship-policy.txt
> +Issue link: httpshttps://github.com/openssl/general-policies/pull/46
Is httpshttps a new protocol :-)
Typo should be fixed.

2023-10-18 08:50 UTC, levitte approved these changes

2023-11-08 14:59 UTC, mattcaswell approved these changes

2023-11-08 15:00 UTC, mattcaswell commented
Pushed.

2023-11-08 15:00 UTC, closed without merging